name: Daily Cron Digest

on:
  schedule:
    # Run daily at 09:00 Europe/Kyiv (06:00 UTC in winter, 07:00 UTC in summer)
    # Using 06:00 UTC to account for standard time
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  call-cron-endpoint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Call digest cron endpoint
      run: |
        curl -X GET "https://yt-digest-bot-web.onrender.com/cron/digest" \
          -H "X-CRON-KEY: ${{ secrets.CRON_KEY }}" \
          -H "Content-Type: application/json" \
          -v
